// micro-app-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { assetUrl } from 'src/single-spa/asset-url';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent {
  imgSrc = assetUrl("Circle.jpg");
  title = 'micro-app-angular';

  menus = [
    {
      key: "angular",
      route: "/",
      title: "主页"
    },
    {
      key: "angular-list",
      route: "/list",
      title: "列表页"
    }
  ]

  get currentRoute() {
    const menu = this.menus.find(item => item.route === window.location.pathname)
    return menu ? menu.key : "angular";
  }

  constructor() {
    console.log('app component ts', this.imgSrc);
  }
}

<section>
  <ul nz-menu nzMode="horizontal" nzTheme="dark">
    <li *ngFor="let item of menus" nz-menu-item [nzSelected]="currentRoute === item.key">
      <a [routerLink]="item.route">{{item.title}}</a>
    </li>
  </ul>
  <img class="test" width="40" src="../assets/Circle.jpg">
  <!-- <img class="test" width="40" src="./assets/logo.png"> -->
  <img class="test" width="40" [src]="imgSrc">
  <img class="test" width="40" src="http://localhost:10300/assets/Delete.jpg">
  <img class="test" width="40" src="http://localhost:10200/img/logo.82b9c7a5.png">
  <section style="padding: 20px;">
    <router-outlet></router-outlet>
  </section>
</section>

// micro-app-vue/src/App.vue
<template>
  <div id="app">
     <a-menu :selectedKeys="[currentRoute]" mode="horizontal" theme="dark">
      <a-menu-item 
        v-for="(item) in menus" 
        :key="item.key"
        >
        <router-link :to="item.route">{{item.title}}</router-link>
      </a-menu-item>
     </a-menu>
     <img class="test" width="40" src="./assets/logo.png">
    <router-view :key="(new Date()).getTime()" />
  </div>
</template>

<script>
export default {
  name: 'App',

  data() {
    return {
      menus: [
        {
          key: "vue",
          route: "/",
          title: "主页"
        },
        {
          key: "vue-list",
          route: "/list",
          title: "列表页"
        }
      ]
    }
  },

  computed: {
    currentRoute() {
      const menu = this.menus.find(item => item.route === this.$route.path)
      return menu ? menu.key : "vue";
    }
  },
}
</script>

<style>
</style>
